name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022
    permissions: 
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Python installer
        run: |
          curl -L -o python-3.13.5-amd64.exe https://www.python.org/ftp/python/3.13.5/python-3.13.5-amd64.exe

      - name: Download Ghostscript installer
        run: |
          curl -L -o gs10051w64.exe https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10051/gs10051w64.exe

      - name: Ensure requirements.txt is present
        run: |
          if (!(Test-Path requirements.txt)) { exit 1 }
        shell: pwsh

      - name: Ensure compress_qt.py is present
        run: |
          if (!(Test-Path compress_qt.py)) { exit 1 }
        shell: pwsh

      - name: Ensure CompressPDF.iss is present
        run: |
          if (!(Test-Path CompressPDF.iss)) { exit 1 }
        shell: pwsh

      - name: Build Windows Installer with iscc
        run: |
          iscc CompressPDF.iss

      - name: List installer files
        run: dir Output
        shell: pwsh

      - name: Upload Installer as Release Asset
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            Output/QCompressPDF.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}