name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Python installer
        run: |
          curl -L -o python-3.13.5-amd64.exe https://www.python.org/ftp/python/3.13.5/python-3.13.5-amd64.exe

      - name: Download Ghostscript installer
        run: |
          curl -L -o gs10051w64.exe https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10051/gs10051w64.exe

      - name: Ensure requirements.txt is present
        run: |
          if not exist requirements.txt exit 1

      - name: Ensure compress_qt.py is present
        run: |
          if not exist compress_qt.py exit 1

      - name: Ensure CompressPDF.iss is present
        run: |
          if not exist CompressPDF.iss exit 1

      - name: Build Windows Installer with iscc
        run: |
          iscc CompressPDF.iss

      - name: Upload Installer as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: QCompressPDF.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 